image: fpco/stack-build:lts-15

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack-work
    - .stack

build:
  stage: build
  script:
    - stack build
    - cp $(stack path --dist-dir)/build/mock/mock .
  artifacts:
    paths:
      - mock
