variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

build:
  tags:
    - nix
  script:
    - nix build .#default
    - cp -Hr result out
  artifacts:
    paths:
      - out

pages:
  stage: deploy
  dependencies: []
  image: node:alpine
  script:
    - npm install swagger-ui-dist
    - cp -r node_modules/swagger-ui-dist public
    - cp web/openapi.yaml public
    - sed -i "s#https://petstore\.swagger\.io/v2/swagger\.json#openapi.yaml#g" public/swagger-initializer.js
  artifacts:
    paths:
      - public
  only:
    - master
