variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

build:
  stage: build
  image: fpco/stack-build:19.31
  script:
    - stack build
    - cp $(stack path --local-install-root)/bin/mock .
    - cp $(stack path --local-install-root)/bin/mock-web .
  artifacts:
    paths:
      - mock
      - mock-web
  cache:
    paths:
      - .stack-work
      - .stack

docker:
  stage: deploy
  dependencies:
    - build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:latest
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - master

pages:
  stage: deploy
  dependencies: []
  image: node:alpine
  script:
    - npm install swagger-ui-dist
    - cp -r node_modules/swagger-ui-dist public
    - cp web/openapi.yaml public
    - sed -i "s#https://petstore\.swagger\.io/v2/swagger\.json#openapi.yaml#g" public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
