name: mock
version: 3.7.1
license: WTFPL
git: https://git.eisfunke.com/software/mock
author: Nicolas Lenz
maintainer: nicolas@eisfunke.com
copyright: 2018-2020 Nicolas Lenz

synopsis: GrEAt HAskeLL PrOGRaM to trANsForm tEXT
category: Text
description: Please see the README at <https://git.eisfunke.com/software/mock>.

dependencies:
  - base
  - text
  - random
  - hashable

extra-doc-files:
  - README.md

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  mock:
    source-dirs: app
    main: main.hs
    dependencies:
      - mock
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  mock-web:
    source-dirs: web
    main: main.hs
    dependencies:
      - mock
      - yesod-core
      - warp
      - wai-extra
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
