name:                mock
version:             3.2.0
license:             WTFPL
git:                 "https://git.eisfunke.com/software/mock"
author:              "Nicolas Lenz"
maintainer:          "nicolas@eisfunke.com"
copyright:           "2018 Nicolas Lenz"

extra-source-files:
- README.md

synopsis:            GrEAt HAskeLL PrOGRaM to trANsForm tEXT
category:            String
description:         Please see the README at <https://git.eisfunke.com/software/mock#readme>

dependencies:
- base >= 4.7 && < 5
- random
- hashable
- text

library:
  source-dirs: src

executables:
  mock:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mock
