name: mock
version: 3.5.0
license: WTFPL
git: https://git.eisfunke.com/software/mock
author: Nicolas Lenz
maintainer: nicolas@eisfunke.com
copyright: 2018-2019 Nicolas Lenz

synopsis: GrEAt HAskeLL PrOGRaM to trANsForm tEXT
category: String
description: Please see the README at <https://git.eisfunke.com/software/mock#readme>.

dependencies:
  - base
  - text
  - random
  - hashable

extra-doc-files:
  - README.md

library:
  source-dirs: src

executables:
  mock:
    main: Main.hs
    source-dirs: app
    dependencies:
      - mock
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
